### ISSUE TITLE
Add Config to change the hightlight of Block render

### ISSUE THREAD

**Issue by Chtholly** [3TUSK/PlacementPreview#4]
Would be nice if we could change the hightlight of the render, cause some renders lokks same like the placed blocks.

**Comment by 3TUSK** [comment]
I would like to know what are those blocks.

**Comment by 3TUSK** [comment]
1.3.0 is now available at https://github.com/3TUSK/PlacementPreview/releases/tag/1.3.0
Before CurseForge approves it, you can get the new version here. Let me know if this is what you want, so I can close this ticket.

---

CurseForge: https://www.curseforge.com/minecraft/mc-mods/place-preview/files/2975672

**Comment by 3TUSK** [comment]
In case you have other issues, please open a new ticket. Gonna close this one for now.
