### ISSUE TITLE
Crashes on server.

### ISSUE THREAD

**Issue by GiantLuigi4** [3TUSK/PlacementPreview#5]
```
[12:22:59] [Server thread/FATAL] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/renderer/IRenderTypeBuffer$Impl for invalid dist DEDICATED_SERVER
[12:22:59] [Server thread/ERROR] [ne.mi.fm.ja.FMLModContainer/LOADING]: Failed to load class info.tritusk.PlacePreview
java.lang.RuntimeException: Attempted to load class net/minecraft/client/renderer/IRenderTypeBuffer$Impl for invalid dist DEDICATED_SERVER
```

**Comment by 3TUSK** [comment]
~~Are you sure you are using latest version?~~

Nvm, I have fixed it but didn't release a new version. Expect a new version in next 24 hours.

*Remark to people seeking support in future: this mod should not be installed on server anyway. It will do nothing on server you insist to install.*

**Comment by 3TUSK** [comment]
https://github.com/3TUSK/PlacementPreview/releases/tag/1.3.0
Before CurseForge approves it, you can get the new version here. Let me know if it works so I can close this ticket.

---

CurseForge: https://www.curseforge.com/minecraft/mc-mods/place-preview/files/2975672

**Comment by 3TUSK** [comment]
In case you have other issues, please open a new ticket. Gonna close this one for now.
