### ISSUE TITLE
[Port request] Permission for me to fork this and port it...

### ISSUE THREAD

**Issue by guivnf** [3TUSK/PlacementPreview#7]
Hey so i'm working on a modpack and i really wanted to include this feature inside of my modpack, but it seems like the mod is locked under an ARR license and you haven't updated it in a while too, wanted to respectfully ask you if i cant have permission to fork this project and port it to newer version, as to also republish it inside of CF & perhaps modrinth in the future too :) 

Anyway, thanks for your answer...

**Comment by 3TUSK** [comment]
It actually has a license. Not at an usual place, though.

Please check the header of the only source file of the mod: https://github.com/3TUSK/PlacementPreview/blob/bleeding/src/main/java/info/tritusk/PlacePreview.java

**Comment by guivnf** [comment]
> It actually has a license. Not at an usual place, though.
> 
> Please check the header of the only source file of the mod: https://github.com/3TUSK/PlacementPreview/blob/bleeding/src/main/java/info/tritusk/PlacePreview.java

Oh yeah, was looking on your CurseForge page and kinda mistook the license as everything ebing ARR. Well in that case, ig i have your permission to fork it and republish it, thanks :)
